# Generated by Django 4.0.1 on 2022-02-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_parse', '0002_savemodel_alter_mymodel_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaveModel',
            new_name='AskModel',
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='category',
            field=models.CharField(choices=[('newstories', 'newstories'), ('jobstories', 'jobstories'), ('showstories', 'showstories'), ('askstories', 'askstories')], default='none', max_length=20),
        ),
    ]
