# Generated by Django 4.0.1 on 2022-02-03 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_parse', '0004_askmodel_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askmodel',
            name='post_id',
        ),
    ]
