# Generated by Django 4.0.1 on 2022-02-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_parse', '0005_remove_askmodel_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='askmodel',
            name='post_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
