# Generated by Django 4.0.1 on 2022-02-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_parse', '0006_askmodel_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='askmodel',
            name='by',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='askmodel',
            name='descendants',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='askmodel',
            name='kids',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='askmodel',
            name='score',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='askmodel',
            name='text',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='askmodel',
            name='time',
            field=models.CharField(default='nuul', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='askmodel',
            name='title',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='askmodel',
            name='type',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='askmodel',
            name='url',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
