# Generated by Django 4.0.1 on 2022-02-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_parse', '0007_askmodel_by_askmodel_descendants_askmodel_kids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=200)),
                ('descendants', models.CharField(max_length=200)),
                ('post_id', models.CharField(max_length=200)),
                ('kids', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=200)),
                ('post_id', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=200)),
                ('post_id', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('descendants', models.CharField(max_length=200)),
                ('kids', models.CharField(max_length=200)),
            ],
        ),
    ]
