# Generated by Django 4.0.1 on 2022-02-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_parse', '0009_newsmodel_descendants'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='kids',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
