# Generated by Django 4.0.1 on 2022-02-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_parse', '0010_newsmodel_kids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askmodel',
            name='url',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='descendants',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='kids',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='text',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='text',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='askmodel',
            name='descendants',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='askmodel',
            name='kids',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='askmodel',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='descendants',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='kids',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='showmodel',
            name='descendants',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='showmodel',
            name='kids',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='showmodel',
            name='text',
            field=models.TextField(),
        ),
    ]
